### ISSUE TITLE
User input values are not checked for validity

### ISSUE THREAD

**Issue by JanneNiemela** [LetsBuildRockets/FlightCalc#2]
-You can assign negative numbers to every input field. 
-Inputting large values cause errors in results. 
(For example inputting 9999999999 in the "M0"-field while the other input fields are set to default values the printed results are these: 1.8354891833602707E-8, 0.0)

**Comment by robstolarz** [comment]
That result makes sense. If you set the mass of the rocket that high, it probably won't fly up too far...
